# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TestProject' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON'
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'FoldingCell'
  pod 'expanding-collection'
  pod 'PopupController'
  pod 'LTMorphingLabel'
  pod 'Kingfisher', '~> 2.4'
  pod 'SwiftPhotoGallery'
  pod 'NVActivityIndicatorView'
  pod 'KCFloatingActionButton'
  pod 'RAMAnimatedTabBarController'
  pod 'LocationPickerViewController'
  pod 'ImagePicker'
  pod 'Firebase/Storage'
  pod 'AsyncSwift'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'JSQMessagesViewController'
end
